databases:
  - name: mdm-db
    plan: free
    databaseName: mdm
    user: mdm

services:
  - type: web
    name: mdm-server
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && npx react-scripts build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: APNS_MOCK
        value: "true"
      - key: BASE_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mdm-db
          property: connectionString
